apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: salvadorsuz/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*.js": .
        "**/*.css": .
        "**/*.html": .
